### ISSUE TITLE
Find list of Web Socket libraries in Java

### ISSUE THREAD

**Issue by AetherialMist** [BlackburnCollege/zoot-tube#2]
Gather a list of potential libraries that implement Web Sockets in Java. Add links to the download site as comments to this issue. Java may have some prebuilt functions? socket.io? WebSockets?

**Comment by lane-ends** [comment]
https://github.com/facundofarias/awesome-websockets#java-vm

**Comment by Rylee-Wilson** [comment]
https://github.com/facundofarias/awesome-websockets#java-vm

https://github.com/facundofarias/awesome-websockets#java-vm

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_a_WebSocket_server_in_Java
