### ISSUE TITLE
Throwaway YouTube Channel for testing

### ISSUE THREAD

**Issue by AetherialMist** [BlackburnCollege/zoot-tube#5]
Create a YouTube Channel that can hold test videos and playlists for our app to utilize for testing.

**Comment by TylerBraden** [comment]
Channel is created. Login credentials are on discord. I have used my personal phone number and my blackburn email as authentication tools. I can create some videos to add to the channel.

**Comment by TylerBraden** [comment]
Channel playlist has been created with 6 pointless videos.

**Comment by TylerBraden** [comment]
Waiting on "unlisted" or "public" clarification before closing the issue.

**Comment by AetherialMist** [comment]
Blocked until we have access to a shared Blackburn account. This is being worked on by Dr. Coogan.
